### PR TITLE
clean up and playability enhancements

### PR DESCRIPTION
**Pull request by kolohelios**

### CODE REVIEW

**Comment by SarahJessica** [comment]
Hi Jon

Thank you for this. Did you add the wrong index.jade file accidentally. It appears to be a stock-trading app.

Jessica :c\

**Comment by kolohelios** [comment]
Hey Jess! Not to my knowledge – that’s strange.

This is what I show for the commit I sent you a PR for: 
https://github.com/kolohelios/wonderlandMemoryGame/blob/master/client/index.jade https://github.com/kolohelios/wonderlandMemoryGame/blob/master/client/index.jade

We might have started the wonderland app from a stock-trading app that you and Clyde worked on?
https://github.com/SarahJessica/wonderlandMemoryGame/commits/master/client/index.jade?author=Cmarl https://github.com/SarahJessica/wonderlandMemoryGame/commits/master/client/index.jade?author=Cmarl

It also looks like there are some merge conflicts including in the code in your repo. We may have introduced those while we were trying to scramble and get the game finished.

Anyway, I hope all is well and that you’re staying cool; I heard about the heatwave London is experiencing right now. 

Jon

**Comment by SarahJessica** [comment]
Hi Jon
Apologies for the delay.
Thank you for taking the time to improve this. 
I have merged the changes but they are not without error. Can't get gulp to run so I have pushed them to a new branch.
If you remember this was the first paired project we ever worked on so I we couldn't have used Clyde's stocktrader app beforehand. I don't know what happened there. :question: 
Jessica :)

**Comment by kolohelios** [comment]
No problem. :) That’s so weird about what happened with the stock market app. I found some old merge conflict issues that made their way back into the codebase; they were throwing LESS and jsHint errors. I got them cleaned them up so this should work now. It looks like it should automatically merge for you.

Warm regards,
Jon

**Pull request closed without merging**
